/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./layouts/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "text-9xl",
    "from-orange-100",
    "to-orange-200",
    "from-rose-100",
    "to-rose-200",
    "from-purple-100",
    "to-purple-200",
    "from-blue-100",
    "to-blue-200",
    "from-sky-100",
    "to-sky-200",
    "bg-orange-100",
    "bg-orange-200",
    "bg-rose-100",
    "bg-rose-200",
    "bg-purple-100",
    "bg-purple-200",
    "bg-blue-100",
    "bg-blue-200",
    "bg-sky-100",
    "bg-sky-200",
    "text-orange-400",
    "text-rose-400",
    "text-purple-400",
    "text-blue-400",
    "text-sky-400",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
