import "@/styles/index.scss";
import Head from "next/head";
import type { AppProps } from "next/app";
import { Quicksand } from "next/font/google";
import Header from "@/components/Header";

const quicksand = Quicksand({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div
      className={`${quicksand.className} relative max-w-screen-sm mx-auto min-h-[100vh] font-sm text-base tracking-wide bg-orange-50`}
    >
      <Head>
        <title>Tarot Interpreter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Component {...pageProps} />
    </div>
  );
}
